from odoo import models, api

class BudgetQueryExecutor(models.AbstractModel):
    _name = "ai.budget.executor"
    _description = "Executes budget queries generated by AI"

    @api.model
    def execute(self, instruction):
        """
        instruction: dict
        Expected keys:
        - action: 'sum', 'list', 'compare', 'top'
        - type: 'fonctionnement' | 'investissement' | 'dette' | 'any'
        - year: int | None
        - year_compare: int | None
        - limit: int | None
        """

        BudgetLine = self.env['crossovered.budget.lines']

        # Base domain
        domain = []
        if instruction.get('year'):
            year = instruction['year']
            domain += [('date_from', '<=', f'{year}-12-31'), ('date_to', '>=', f'{year}-01-01')]
        if instruction.get('type') and instruction['type'] != 'any':
            domain += [('crossovered_budget_id.type_budget', '=', instruction['type'])]

        lines = BudgetLine.search(domain)

        action = instruction.get('action')

        if action == 'sum':
            total = sum(line.planned_amount or 0.0 for line in lines)
            return {'sum': total}

        elif action == 'list':
            result = []
            for line in lines:
                result.append({
                    'budget_name': line.crossovered_budget_id.name,
                    'line_name': line.general_budget_id.name if line.general_budget_id else None,
                    'planned_amount': line.planned_amount,
                    'practical_amount': line.practical_amount,
                    'date_from': line.date_from,
                    'date_to': line.date_to,
                })
            return {'lines': result}

        elif action == 'compare':
            year_compare = instruction.get('year_compare')
            if not year_compare:
                raise ValueError("year_compare is required for compare action")
            # Query the second year
            domain_compare = domain.copy()
            domain_compare = [d for d in domain_compare if not d[0].startswith('date_')]
            domain_compare += [('date_from', '<=', f'{year_compare}-12-31'), ('date_to', '>=', f'{year_compare}-01-01')]
            lines_compare = BudgetLine.search(domain_compare)

            sum1 = sum(line.planned_amount or 0.0 for line in lines)
            sum2 = sum(line.planned_amount or 0.0 for line in lines_compare)
            return {'year1': instruction['year'], 'year2': year_compare, 'sum1': sum1, 'sum2': sum2}

        elif action == 'top':
            limit = instruction.get('limit', 5)
            sorted_lines = sorted(lines, key=lambda l: l.planned_amount or 0, reverse=True)
            result = [{
                'budget_name': l.crossovered_budget_id.name,
                'line_name': l.general_budget_id.name if l.general_budget_id else None,
                'planned_amount': l.planned_amount
            } for l in sorted_lines[:limit]]
            return {'top_lines': result}

        else:
            raise ValueError(f"Unknown action: {action}")
